<?php
/**
 * Created by PhpStorm.
 * User: Asus
 * Date: 14/01/2018
 * Time: 10:09
 */

class Valeur{
    protected $nom;
    protected $prix;

    public function __construct($nom,$prix)
    {
        $this->nom=$nom;
        $this->prix=$prix;
    }
    public function affichage(){
        echo "nom=".$this->nom." et prix=".$this->prix;
    }
}

class Fille extends Valeur{
    private $bourse;
    public function __construct($nom, $prix, $bourse)
    {
        parent::__construct($nom, $prix);
        $this->bourse=$bourse;
    }
    public function affichage()
    {
        parent::affichage(); // TODO: Change the autogenerated stub
        echo " et bourse=".$this->bourse. "<br>";
    }
}

class emprunt extends Valeur{
    private $taux;
    private $fin;
    public function __construct($nom, $prix, $taux, $fin)
    {
        parent::__construct($nom, $prix);
        $this->taux=$taux;
        $this->fin=$fin;
    }

    public function affichage()
    {
        parent::affichage(); // TODO: Change the autogenerated stub
        echo " taux=".$this->taux." fin=".$this->fin. "<br>";
    }
}

$action1=new Valeur("book","8.500");
$action2=new Fille("mac","2000","123");
$emprunt=new emprunt("asus","1500","10","20");

$action1->affichage();
echo "<br>";
$action2->affichage();
$emprunt->affichage();